esphome:
  name: "seelevel"
  friendly_name: "seelevel"

external_components:
  - source:
      type: local
      path: components
  # - source: github://j9brown/esphome-seelevel@main
  #   components: [ seelevel ]

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true

api:
  encryption:
    key: "h0D1UztdOrV5Ve+CIQWDVok952l+fDsm8gCjGTZjVEs="

ota:
  password: "5179ff516528e4a163dae07f0b19aeeb"

seelevel:
  id: seelevel_transceiver
  rx_pin: 32
  tx_pin: 33

sensor:
  - platform: seelevel
    seelevel_id: seelevel_transceiver
    tank: 2
    segments: 9
    level:
      name: "Water Level"
      filters:
        - sliding_window_moving_average:
            window_size: 5
            send_every: 5
        - delta: 0.1
    volume:
      name: "Water Volume"
      map:
        - { level: 4.0, volume: 25 L }
        - { level: 9.0, volume: 40 L }
      filters:
        - sliding_window_moving_average:
            window_size: 5
            send_every: 5
        - delta: 0.25
    segment_data:
      name: "Segment Data"
    update_interval: 0.5s
